baseURL = "https://blog.sinnathurai.ch/"
languageCode = "de-ch"
title = "Pratheep's Tech Blog"
theme = "ananke"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Pratheep Sinnathurai"
  description = "Sharing is Caring"
  github = "psinnathurai"
  twitter = "psinnathurai"
  linkedin = "psinnathurai"
  url = "https://medium.com/@psinnathurai"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/github-mark.png"
  avatar = "/images/me/pratheep.png"
  headerIcon = "/images/github-mark.png"
  location = "Switzerland"
